version: "3.9"
services:
  disces:
    image: ghcr.io/rebesatt/disces:latest
    volumes:
      - .:/app
    working_dir: /app

  disces_long:
    image: ghcr.io/rebesatt/disces:latest
    command: ["-ilm"]
    volumes:
      - .:/app
    working_dir: /app