name: Run experiments and produce PDF

on:
  workflow_dispatch:
    inputs:
      include_long:
        description: "Run long experiments (-ilm)?"
        type: boolean
        default: false

permissions:
  contents: read
  packages: read   # needed to pull from GHCR
  actions: read

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/disces:latest

      - name: Run container (default or -ilm)
        env:
          INCLUDE_LONG: ${{ inputs.include_long }}
        run: |
          set -euo pipefail
          # mount the workspace so the PDF ends up in the repo tree on the runner
          MOUNT="-v ${{ github.workspace }}:/app -w /app"
          IMAGE="ghcr.io/${{ github.repository_owner }}/disces:latest"

          if [ "${INCLUDE_LONG}" = "true" ]; then
            echo "Running with -ilm..."
            docker run --rm $MOUNT "$IMAGE" -ilm
          else
            echo "Running default experiments..."
            docker run --rm $MOUNT "$IMAGE"
          fi

      - name: List produced files (debug)
        run: |
          ls -lah docs/latex_src || true
          ls -lah docs/latex_src/out || true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: |
            docs/latex_src/main.pdf
            docs/latex_src/out/main.pdf
          if-no-files-found: warn